### ISSUE TITLE
Jocul "Find Words" nu se salvează corespunzător

### ISSUE THREAD

**Issue by CristianSimion5** [CristianSimion5/mds-maps#31]
Timer-ul continuă chiar și atunci când se iese din ecranul jocului.

**Comment by MarianGiugioiu** [comment]
Rezolvat. Am modificat salvarea automata la un interval de timp. Acum datele se vor salva atunci cand se apasa pe butonul "inapoi" al aplicatiei sau cel al telefonului sau atunci cand se iese din aplicatie. De asemenea am rezolvat si problema cu timerul care continua sa mearga si atunci cand aplicatia era in background.
